# Hyperparameter grids for tuning

random_forest:
  n_estimators: [50, 100, 200]
  max_depth: [null, 10, 20, 30]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]

decision_tree:
  max_depth: [null, 5, 10, 15, 20]
  min_samples_split: [2, 5, 10, 20]
  min_samples_leaf: [1, 2, 5, 10]
  criterion: ["gini", "entropy"]

svm:
  C: [0.1, 1, 10, 100]
  gamma: ["scale", "auto", 0.001, 0.01, 0.1, 1]
  kernel: ["rbf", "linear", "poly"]
